# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets, QtGui
from ChatApp.main_window import Ui_MainWindow
from ChatApp.global_variables import user

global user


class Ui_StartWindow(object):

    def setupUi(self, StartWindow):
        self.StartWindow = StartWindow
        self.StartWindow.setObjectName("StartWindow")
        self.StartWindow.setEnabled(True)
        self.StartWindow.resize(450, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartWindow.sizePolicy().hasHeightForWidth())
        self.StartWindow.setSizePolicy(sizePolicy)
        self.StartWindow.setMinimumSize(QtCore.QSize(450, 300))
        self.StartWindow.setMaximumSize(QtCore.QSize(450, 300))
        self.centralwidget = QtWidgets.QWidget(self.StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.push_button_register = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.clicked_register())
        self.push_button_register.setGeometry(QtCore.QRect(110, 185, 230, 25))
        self.push_button_register.setObjectName("push_button_register")
        self.push_button_login = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.clicked_login())
        self.push_button_login.setGeometry(QtCore.QRect(110, 150, 230, 25))
        self.push_button_login.setObjectName("push_button_login")
        self.line_edit_user_id = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_user_id.setGeometry(QtCore.QRect(190, 80, 150, 25))
        self.line_edit_user_id.setObjectName("line_edit_user_id")
        self.line_edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_password.setGeometry(QtCore.QRect(190, 115, 150, 25))
        self.line_edit_password.setObjectName("line_edit_password")
        self.label_user_id = QtWidgets.QLabel(self.centralwidget)
        self.label_user_id.setGeometry(QtCore.QRect(110, 80, 80, 25))
        self.label_user_id.setObjectName("label_user_id")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(110, 115, 80, 25))
        self.label_password.setObjectName("label_password")
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        self.label_heading.setGeometry(QtCore.QRect(115, 20, 220, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_heading.setFont(font)
        self.label_heading.setText("Python ChatApp")
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(25, 235, 400, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.StartWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.StartWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.StartWindow.setWindowTitle(_translate("StartWindow", "Python ChatApp"))
        self.push_button_register.setText(_translate("StartWindow", "Register"))
        self.push_button_login.setText(_translate("StartWindow", "Login"))
        self.label_user_id.setText(_translate("StartWindow", "User ID:"))
        self.label_password.setText(_translate("StartWindow", "Password:"))
        self.label_error.setText(_translate("StartWindow", ""))

    ####################################################################################################################

    """ USER GENERATED CODE STARTS HERE """

    ####################################################################################################################

    # try to login the user | push_button_login
    def clicked_login(self):
        if not user.login(self.line_edit_user_id.text(), self.line_edit_password.text()):
            self.label_error.setText("Wrong user id or password. Please try again.")
        else:
            self.switch_window()

    # try to register the user | push_button_register
    def clicked_register(self):
        if self.line_edit_user_id.text().strip() == "" or self.line_edit_password.text().strip() == "":
            self.label_error.setText("You need a user id and a password. Please fill the boxes.")
        elif not user.create_user(self.line_edit_user_id.text(), self.line_edit_password.text()) or "pytest" in self.line_edit_user_id.text():
            self.label_error.setText("This user id already exists. Please try another id.")

        else:
            self.switch_window()

    # switches to the main window after successful login/registration
    def switch_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(self.window)
        self.ui.setupUi()
        self.window.show()
        self.ui.start_timer()
        self.StartWindow.close()
